#! /bin/sh
./goldd sendtoaddress GZJ3cU6EFs4XNZFqoSwJX7RYbCYXawGaFa 207297
./goldd sendtoaddress GeGadpNekZTXkVnJtLWbBC58SmL13FtWWo 248154
./goldd sendtoaddress GJF9i7vPkxKwYJY4C7SkGcHkzYeKaeRdV4 48069